services:

  redis:
    image: redis:alpine3.17
    container_name: redis
    restart: always
    ports:
      - 8081:6379
    volumes:
      - ./redis/data:/data
      - ./redis/conf/redis.conf:/usr/local/etc/redis/redis.conf

  app:
    build: .
    ports:
      - "8080:8000"
    volumes:
      - ./app:/srv/app:ro
    environment:
      - PORT=8000
      - HOST=0.0.0.0
      - REDIS_URL=redis://redis:6379/0
    depends_on:
      - redis
